/*
 * todo.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RecordStatus string

// List of RecordStatus
const (
	TODO RecordStatus = "STATUS_TODO"
	INPROGRESS RecordStatus = "STATUS_INPROGRESS"
	DONE RecordStatus = "STATUS_DONE"
)
