/*
 * todo.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type TodoRecordInput struct {

	Id int32 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Detail string `json:"detail,omitempty"`

	Deadline time.Time `json:"deadline,omitempty"`
}
