/*
 * practice-grpc-and-web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type TodoRecord struct {

	Id int32 `json:"id"`

	CreatedAt time.Time `json:"created_at"`

	Title string `json:"title"`

	Detail string `json:"detail"`

	Deadline time.Time `json:"deadline"`

	Status *RecordStatus `json:"status"`
}
