/*
 * practice-grpc-and-web
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type TodoQueryRequest struct {

	Start time.Time `json:"start,omitempty"`

	End time.Time `json:"end,omitempty"`
}
